In [2]:
import numpy as np
import time

# VECTORS

In [3]:
# NumPy vetor creation, will allocate memory and fill array with value
a = np.zeros(4)
print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
# so shape is a single tuple of size 4 shape(4,)

a = np.zeros((4,))
print(f"np.zeros(4,) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

a = np.random.random_sample(4)
print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.30947298 0.9612676  0.23922837 0.97380588], a shape = (4,), a data type = float64


In [4]:
# NumPy routines which allocate memory and fill arrays with value but do not accept shape as input argument
a = np.arange(4.)
print(f"np.arange(4.):     a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

a = np.random.rand(4)
print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

# NumPy routines which allocate memory and fill with user specified values
a = np.array([[5,4,3,2], [1,2,3,4]]);  print(f"np.array([5,4,3,2]):  a = {a},     a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5.,4,3,2]);              print(f"np.array([5.,4,3,2]): a = {a},     a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.):     a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.93643776 0.51012379 0.41174496 0.53304375], a shape = (4,), a data type = float64
np.array([5,4,3,2]):  a = [[5 4 3 2]
 [1 2 3 4]],     a shape = (2, 4), a data type = int64
np.array([5.,4,3,2]): a = [5. 4. 3. 2.],     a shape = (4,), a data type = float64


In [5]:
# Operations on Vectors

# Indexing
a = np.arange(10)
print(a)

#access an element
print(f"a[2].shape: {a[2].shape} a[2]  = {a[2]}, Accessing an element returns a scalar")

# access the last element, negative indexes count from the end
print(f"a[-1] = {a[-1]}")
print(f"a[-2] = {a[-2]}")


[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2]  = 2, Accessing an element returns a scalar
a[-1] = 9
a[-2] = 8


In [6]:
#indexs must be within the range of the vector or they will produce and error
try:
    c = a[10]
except Exception as e:
    print("The error message you'll see is:")
    print(e)

The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


In [7]:
# Operations on Vectors cont.

# slciing 
a = np.arange(10)
print(a)

#access 5 consecutive elements (start:stop:step)
c = a[2:7:1]
print(c)

#access 3 elements separated by 2
c = a[2:7:2]
print(c)

#acess all elements index 3 and above
c = a[3:]
print(c)

#acess all elements below 3
c = a[:3]
print(c)

#access all elements 
c = a[:]
print(c)


[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6]
[2 4 6]
[3 4 5 6 7 8 9]
[0 1 2]
[0 1 2 3 4 5 6 7 8 9]


In [8]:
# single vector operations 

a = np.array([1,2,3,4])
print (a)

#negate elements of a
b = -a
print(b)

#sum elements of a, returns a scalar
b = np.sum(a)
print(b)

#mean of a, returns scalar
b = np.mean(a)
print (b)

# returns each elements raised to its own power 
b = a**2
print(b)

[1 2 3 4]
[-1 -2 -3 -4]
10
2.5
[ 1  4  9 16]


In [9]:
# vector vector element wise operations

a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(a + b)

#try a mismatched vector operation
c = np.array([1, 2])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)


#scalar

a = np.array([1, 2, 3, 4])

# multiply a by a scalar
b = 5 * a 
print(f"b = 5 * a : {b}")

[0 0 6 8]
The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 
b = 5 * a : [ 5 10 15 20]


In [10]:
#def dot product, our own function not NumPy

def my_dot(a, b): 
    """
   Compute the dot product of two vectors
 
    Args:
      a (ndarray (n,)):  input vector 
      b (ndarray (n,)):  input vector with same dimension as a
    
    Returns:
      x (scalar): 
    """
    x=0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

In [11]:
# test 1-D
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
print(my_dot(a,b))

#now test numpy dot
c = np.dot(a,b)
print(c)

24
24


In [15]:
#speed test, NumPy vs def 
np.random.seed(1)
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()  # capture start time
c = np.dot(a, b)
toc = time.time()  # capture end time

print(f"np.dot(a, b) =  {c:.4f}")
t1 = 1000*(toc-tic)
print(f"Vectorized version duration: {t1:.4f} ms ")

tic = time.time()  # capture start time
c = my_dot(a,b)
toc = time.time()  # capture end time

print(f"my_dot(a, b) =  {c:.4f}")
t2 = 1000*(toc-tic)
print(f"loop version duration: {t2:.4f} ms ")

percent_increase = ((t2 - t1) / t1) * 100
print(f"percent increase {percent_increase:.2f} percent")

del(a)
del(b)
del(t1,t2)




np.dot(a, b) =  249825.0234
Vectorized version duration: 0.7081 ms 
my_dot(a, b) =  249825.0234
loop version duration: 148.1400 ms 
percent increase 20820.67 percent


# Matricies

In [17]:
a = np.zeros((1, 5))                                       
print(f"a shape = {a.shape}, a = {a}")                     

a = np.zeros(5)                                       
print(f"a shape = {a.shape}, a = {a}")  

a = np.zeros((2, 1))                                                                   
print(f"a shape = {a.shape}, a = {a}") 

a = np.random.random_sample((1, 1))  
print(f"a shape = {a.shape}, a = {a}") 

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (5,), a = [0. 0. 0. 0. 0.]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.76080423]]


In [18]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([[5], [4], [3]]);   print(f" a shape = {a.shape}, np.array: a = {a}")
a = np.array([[5],   # One can also
              [4],   # separate values
              [3]]); #into separate rows
print(f" a shape = {a.shape}, np.array: a = {a}")

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


In [22]:
# indexing matricies

#vector indexing operations on matrices
a = np.arange(6).reshape(-1, 2)   #reshape is a convenient way to create matrices
print(f"a.shape: {a.shape}, \na= {a}")

#access an element
print(f"\na[2,0].shape:   {a[2, 0].shape}, a[2,0] = {a[2, 0]},     type(a[2,0]) = {type(a[2, 0])} Accessing an element returns a scalar\n")

#access a row
print(f"a[2].shape:   {a[2].shape}, a[2]   = {a[2]}, type(a[2])   = {type(a[2])}")


a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape:   (), a[2,0] = 4,     type(a[2,0]) = <class 'numpy.int64'> Accessing an element returns a scalar

a[2].shape:   (2,), a[2]   = [4 5], type(a[2])   = <class 'numpy.ndarray'>


 -- the reshape -1 argument tells the reshape to compute the number of rows needed with the given input column

In [27]:
#vector 2-D slicing operations
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

#access 5 consecutive elements (start:stop:step)
print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")

#access 5 consecutive elements (start:stop:step) in two rows
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")

# access all elements
print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

# access all elements in one row (very common usage)
print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
# same as
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")


a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array
